### ISSUE TITLE
Removing gitbook tags from README.md

### ISSUE THREAD

**Issue by avnish98** [MasoniteFramework/docs#12]
I would like to remove git book tags from README.md such as( {% code-tabs %} {% code-tabs-item title="terminal" %} ) because they don't render in markdown.

**Comment by josephmancuso** [comment]
unfortunately they need to be there because gitbook uses them to render in their service.

**Comment by alevis** [comment]
Hi Joseph, sorry for putting this here.
in `part-2-creating-our-first-controller.md`
```
def show(self):
    return view('blog')
```
should be 
```
def show(self):
    return view('Blog')
```

**Comment by josephmancuso** [comment]
@alevis no I don't think so. Why do you think it should be a capital?

**Comment by alevis** [comment]
You're right, the typo is on my end. I think I created a `Blog` view instead of a `blog` view.
