### ISSUE TITLE
[ORM] Schema and Migrations section order in docs

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/docs#129]
Reading the docs of Orm part in Masonite docs I'm a bit confused when the way of uses Model came first than Schema and Migrations ( necessary for creating the tables for uses of Models )

Should'nt they came first than QueryBuilder section?

**Comment by girardinsamuel** [comment]
I am using this issue to report this section as missing now ? @josephmancuso did you removed it ?
* I can't find the schema doc (with all available columns list). 
* Neither the migrations guide (creating a new migrations, and all orm commands)

**Comment by josephmancuso** [comment]
Its here. Must have gotten removed fromn the SUMMARY.md file https://github.com/MasoniteFramework/docs/blob/v3.0/masonite-orm/schema-and-migrations.md

**Comment by girardinsamuel** [comment]
Thanks !

**Comment by girardinsamuel** [comment]
I put it back and changed order of sections as asked
