### ISSUE TITLE
Add warning for soft deletes mixin use

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/docs#143]
I added a warning few weeks ago to explain that when using SoftDeletesScope on a model, you should still define a column "deleted_at" on your model (it's not automatically done). I can't find this warning anymore ? has been removed ?

I would like to add it again, and give an example. We should use datetime field and not timestamp (some people might be mistaken, I made the error myself 🙄 and the list of users was always empty as all users are then created with  a `deleted_at` field not null).

Example of setting the column related to the SoftDeletesScope on the User model:
```python
# user migration
table.datetime("deleted_at").nullable()
```

**Comment by josephmancuso** [comment]
yeah most likely. my fault. I rewrote a lot of the docs the other day.

There should also be a `table.soft_deletes()`

**Comment by girardinsamuel** [comment]
No worries, it's reported here not to forget.
You're right I can add it quickly.
