### ISSUE TITLE
Missing color highlighting for diff

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/docs#149]
Midway down the Masonite 2.3 to 3.0 upgrade page it says:

"If the changes in green already exist then your project is correct. If you have the code in red then make this diff change:"  My browser doesn't display green or red; only strike-through text and (dotted) underlined.

I suspect CSS styles are missing on the documentation site.

**Comment by girardinsamuel** [comment]
It's a change in Gitbook itself. We are using markdown `diff` syntax but they seem to have change the way to display it.
We cannot add gitbook diff plugin on the hosted docs in gitbook.com, so there are no solutions for now.

But we will update the docs to replace this sentence with the correct one as diffs are now displayed like this:
![image](https://user-images.githubusercontent.com/9897999/146639187-65d08c6b-10a5-49a2-88b3-73954215d94f.png)
