### ISSUE TITLE
Missing Resource routes names parameter 

### ISSUE THREAD

**Issue by rickavmaniac** [MasoniteFramework/docs#150]
I was reading Masonite source code and just found something not mention in the doc.  

It is possible to name the routes created by Resource route.

We need to add a dic names parameters in this format {'action':'route name'} 

Here are the syntax:

Resource('contacts', 'ContactsController', names={'index': 'contacts.index'})

We can do that for all the 7 actions

Resource('contacts', 'ContactsController', names={
    'index': 'contacts.index', 
    'show': 'contacts.show',
    'create': 'contacts.create'
    'store': 'contacts.store', 
    'edit': 'contacts.edit',
    'update': 'contacts.update', 
    'destroy': 'contacts.destroy'
}),

**Comment by girardinsamuel** [comment]
That's right ! That has not been ported over to Masonite 4. I will close this issue then. If you think this feature is worth it please open a feature request on masonite repo 🙏.
