### ISSUE TITLE
Improve broadcasting docs

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/docs#198]
I was told there is not a lot of information in the broadcasting docs. Will need to review this

**Comment by girardinsamuel** [comment]
Maybe those improvments are:

Add small snippet for client-side use:
- with vanilla js
- with pusher.js
- warn users that env vars in frontend read from .env and compiled with mix must be prefixed with `MIX_`

Add an example of public broadcasting (front+back)

Add an example of private broadcasting (front+back)
