### ISSUE TITLE
Missing the word filter in adding filters section

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/docs#232]
In features/views.md (and in the [Documentation](https://docs.masoniteproject.com/the-basics/views#adding-filters)) in the Adding Filters section, it is missing the word "filter" in the code example.

It is currently:
```python
    def register(self):
        View.('slug', self.slug)
```

but should be 
```python
    def register(self):
        View.filter('slug', self.slug)
```

This makes it difficult to understand how to get it working.

**Comment by eaguad1337** [comment]
This is solved. Please close the issue. @josephmancuso
