### ISSUE TITLE
Duplicate content or not?

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/docs#4]
These pages contain the same content: [https://docs.masoniteproject.com/](https://docs.masoniteproject.com/) and [https://docs.masoniteproject.com/prologue/introduction-and-installaton](https://docs.masoniteproject.com/prologue/introduction-and-installaton)

**Comment by josephmancuso** [comment]
Yeah it is. Gitbook is dumb and has a "front page" which won't show in the left menu. So it's sort of dumb but we have to keep them in sync until we find a better solution

**Comment by nioperas06** [comment]
Would be better to move [https://docs.masoniteproject.com/prologue/introduction-and-installaton](https://docs.masoniteproject.com/prologue/introduction-and-installaton) to [https://docs.masoniteproject.com/prologue/introduction-and-installation](https://docs.masoniteproject.com/prologue/introduction-and-installaton).

**Comment by josephmancuso** [comment]
yeah do you want access to the gitbook?

**Comment by josephmancuso** [comment]
this way you have a UI to work with

**Comment by nioperas06** [comment]
Let me run my fork with Gitbook. I'll submit a PR.

**Comment by josephmancuso** [comment]
here I think this link should work https://www.gitbook.com/invite/masoniteframework?invite=-L9ubzYTjgqy72WiciqB
